### ISSUE TITLE
Driver stuck in 'continue using manually installed' driver after switching to nouveau. others are greyed out

### ISSUE THREAD

**Issue by ijash** [linuxmint/mintdrivers#51]
I hope this is the proper location to post an issue. if not, please notify me. I will move it later.
```
 * Distribution : Mint 19.03
 * Cinnamon version :  4.4.5
 * 64 bit
 ```

**Issue**
I am getting this message:
![image](https://user-images.githubusercontent.com/30673286/71424895-669bf400-26c9-11ea-8be3-c2033020d928.png)
Then, the driver manager shows:
![image](https://user-images.githubusercontent.com/30673286/71424889-597f0500-26c9-11ea-9c8f-16bac754403c.png)

the problem is, i can't get back to install the nvidia drivers. other options are greyed out.

**Steps to reproduce**
1. after long using nvidia drivers, switch back to nouveau open source driver using the driver manager.
2. restart.
3. open the driver manager, and it's stuck to the manually installed driver. Unable to switch other drivers.  

*note:
this is tested not only in a computer, but other computer as well. with the same mint distribution.*

**Expected behaviour**

Users are freely switching between drivers even if they manually install custom drivers.

**Other information**
this linux mint is upgraded version form 19.02 via update manager.  

system info:
```

System:
  Host: ijash-LM-PC Kernel: 5.0.0-37-generic x86_64 bits: 64 compiler: gcc 
  v: 7.4.0 Desktop: Cinnamon 4.4.5 wm: muffin 4.4.1 dm: LightDM 1.26.0 
  Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic 
Machine:
  Type: Desktop System: Gigabyte product: Z270X-UD3 v: N/A serial: <filter> 
  Mobo: Gigabyte model: Z270X-UD3-CF v: x.x serial: <filter> 
  UEFI: American Megatrends v: F7 date: 07/07/2017 
CPU:
  Topology: Quad Core model: Intel Core i7-7700K bits: 64 type: MT MCP 
  arch: Kaby Lake rev: 9 L2 cache: 8192 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 67200 
  Speed: 800 MHz min/max: 800/4500 MHz Core speeds (MHz): 1: 800 2: 801 
  3: 800 4: 800 5: 800 6: 800 7: 800 8: 800 
Graphics:
  Device-1: NVIDIA GM206 [GeForce GTX 950] vendor: ZOTAC driver: nvidia 
  v: 435.21 bus ID: 01:00.0 chip ID: 10de:1402 
  Display: x11 server: X.Org 1.19.6 driver: nvidia 
  resolution: 1368x768~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: GeForce GTX 950/PCIe/SSE2 v: 4.6.0 NVIDIA 435.21 
  direct render: Yes 
Audio:
  Device-1: Intel 200 Series PCH HD Audio vendor: Gigabyte 
  driver: snd_hda_intel v: kernel bus ID: 00:1f.3 chip ID: 8086:a2f0 
  Device-2: NVIDIA vendor: ZOTAC driver: snd_hda_intel v: kernel 
  bus ID: 01:00.1 chip ID: 10de:0fba 
  Device-3: Yamaha type: USB driver: snd-usb-audio bus ID: 1-7:3 
  chip ID: 0499:1502 
  Sound Server: ALSA v: k5.0.0-37-generic 
Network:
  Device-1: Intel Ethernet I219-V vendor: Gigabyte driver: e1000e v: 3.2.6-k 
  port: f000 bus ID: 00:1f.6 chip ID: 8086:15b8 
  IF: enp0s31f6 state: up speed: 100 Mbps duplex: full mac: <filter> 
Drives:
  Local Storage: total: 4.33 TiB used: 136.73 GiB (3.1%) 
  ID-1: /dev/nvme0n1 vendor: A-Data model: SX8200PNP size: 476.94 GiB 
  speed: 31.6 Gb/s lanes: 4 serial: <filter> rev: S0118C scheme: GPT 
  ID-2: /dev/sda vendor: Samsung model: SSD 850 EVO 250GB size: 232.89 GiB 
  speed: 6.0 Gb/s serial: <filter> rev: 2B6Q scheme: GPT 
  ID-3: /dev/sdb vendor: Western Digital model: WD30EZRZ-00Z5HB0 
  size: 2.73 TiB speed: 6.0 Gb/s rotation: 5400 rpm serial: <filter> 
  rev: 0A82 scheme: GPT 
  ID-4: /dev/sdc vendor: Western Digital model: WD10EZEX-08WN4A0 
  size: 931.51 GiB speed: 6.0 Gb/s rotation: 7200 rpm serial: <filter> 
  rev: 1A02 scheme: GPT 
Partition:
  ID-1: / size: 453.59 GiB used: 85.56 GiB (18.9%) fs: ext4 
  dev: /dev/nvme0n1p2 
  ID-2: swap-1 size: 15.10 GiB used: 0 KiB (0.0%) fs: swap 
  dev: /dev/nvme0n1p1 
Sensors:
  System Temperatures: cpu: 46.0 C mobo: N/A gpu: nvidia temp: 43 C 
  Fan Speeds (RPM): N/A gpu: nvidia fan: 40% 
Repos:
  No active apt repos in: /etc/apt/sources.list 
  Active apt repos in: /etc/apt/sources.list.d/balena-etcher.list 
  1: deb https://deb.etcher.io stable etcher
  Active apt repos in: /etc/apt/sources.list.d/fossfreedom-arc-gtk-theme-daily-bionic.list 
  1: deb http://ppa.launchpad.net/fossfreedom/arc-gtk-theme-daily/ubuntu bionic main
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
  1: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/nodesource.list 
  1: deb https://deb.nodesource.com/node_12.x bionic main
  2: deb-src https://deb.nodesource.com/node_12.x bionic main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
  1: deb http://mirrors.evowise.com/linuxmint/packages tricia main upstream import backport
  2: deb http://mirror.biznetgio.com/ubuntu bionic main restricted universe multiverse
  3: deb http://mirror.biznetgio.com/ubuntu bionic-updates main restricted universe multiverse
  4: deb http://mirror.biznetgio.com/ubuntu bionic-backports main restricted universe multiverse
  5: deb http://security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
  6: deb http://archive.canonical.com/ubuntu/ bionic partner
  Active apt repos in: /etc/apt/sources.list.d/papirus-papirus-bionic.list 
  1: deb http://ppa.launchpad.net/papirus/papirus/ubuntu bionic main
  Active apt repos in: /etc/apt/sources.list.d/spotify.list 
  1: deb http://repository.spotify.com stable non-free
  Active apt repos in: /etc/apt/sources.list.d/teamviewer.list 
  1: deb http://linux.teamviewer.com/deb stable main
  Active apt repos in: /etc/apt/sources.list.d/tista-adapta-bionic.list 
  1: deb http://ppa.launchpad.net/tista/adapta/ubuntu bionic main
  Active apt repos in: /etc/apt/sources.list.d/vscode.list 
  1: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
Info:
  Processes: 269 Uptime: 1h 41m Memory: 15.61 GiB used: 2.32 GiB (14.8%) 
  Init: systemd v: 237 runlevel: 5 Compilers: gcc: 7.4.0 alt: 7 Shell: zsh 
  v: 5.4.2 running in: gnome-terminal inxi: 3.0.32 
```
.xsession-errors info:
```
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting XAUTHORITY=/home/ijash/.Xauthority
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting LC_MEASUREMENT=id_ID.UTF-8
dbus-update-activation-environment: setting LC_PAPER=id_ID.UTF-8
dbus-update-activation-environment: setting LC_MONETARY=id_ID.UTF-8
dbus-update-activation-environment: setting LANG=en_US.UTF-8
dbus-update-activation-environment: setting GDM_LANG=en_US
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting MANDATORY_PATH=/usr/share/gconf/cinnamon.mandatory.path
dbus-update-activation-environment: setting LC_NAME=id_ID.UTF-8
dbus-update-activation-environment: setting XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/ijash
dbus-update-activation-environment: setting USER=ijash
dbus-update-activation-environment: setting DESKTOP_SESSION=cinnamon
dbus-update-activation-environment: setting DEFAULTS_PATH=/usr/share/gconf/cinnamon.default.path
dbus-update-activation-environment: setting PWD=/home/ijash
dbus-update-activation-environment: setting HOME=/home/ijash
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting XDG_SESSION_TYPE=x11
dbus-update-activation-environment: setting XDG_DATA_DIRS=/usr/share/cinnamon:/usr/share/gnome:/home/ijash/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
dbus-update-activation-environment: setting XDG_SESSION_DESKTOP=cinnamon
dbus-update-activation-environment: setting LC_ADDRESS=id_ID.UTF-8
dbus-update-activation-environment: setting LC_NUMERIC=id_ID.UTF-8
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting SHELL=/usr/bin/zsh
dbus-update-activation-environment: setting XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
dbus-update-activation-environment: setting IM_CONFIG_PHASE=1
dbus-update-activation-environment: setting GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
dbus-update-activation-environment: setting SHLVL=1
dbus-update-activation-environment: setting LANGUAGE=en_US
dbus-update-activation-environment: setting LC_TELEPHONE=id_ID.UTF-8
dbus-update-activation-environment: setting GDMSESSION=cinnamon
dbus-update-activation-environment: setting LOGNAME=ijash
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting XDG_RUNTIME_DIR=/run/user/1000
dbus-update-activation-environment: setting XAUTHORITY=/home/ijash/.Xauthority
dbus-update-activation-environment: setting XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
dbus-update-activation-environment: setting XDG_CONFIG_DIRS=/etc/xdg/xdg-cinnamon:/etc/xdg
dbus-update-activation-environment: setting PATH=/home/ijash/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
dbus-update-activation-environment: setting LC_IDENTIFICATION=id_ID.UTF-8
dbus-update-activation-environment: setting _=/usr/bin/dbus-update-activation-environment
[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found

(csd-xrandr:1714): CinnamonDesktop-CRITICAL **: 01:57:50.684: gnome_rr_output_info_get_rotation: assertion 'GNOME_IS_RR_OUTPUT_INFO (self)' failed

(csd-color:1712): color-plugin-WARNING **: 01:57:50.788: failed to get edid: unable to get EDID for output

(csd-color:1712): color-plugin-WARNING **: 01:57:50.956: unable to get EDID for xrandr-DVI-I-0: unable to get EDID for output
Clutter-Message: 01:57:55.282: Sync method: FALLBACK
Cjs-Message: 01:57:55.441: JS LOG: About to start Cinnamon
Cjs-Message: 01:57:55.501: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 58 ms
Cjs-Message: 01:57:55.505: JS LOG: [LookingGlass/info] loading user theme: /usr/share/themes/Arc-Dark/cinnamon/cinnamon.css
Cjs-Message: 01:57:55.514: JS LOG: [LookingGlass/info] added icon directory: /usr/share/themes/Arc-Dark/cinnamon
** Message: 01:57:55.602: nemo-desktop: session is cinnamon, establishing proxy
Cjs-Message: 01:57:55.632: JS LOG: [LookingGlass/info] PlacesManager: Updating devices
Cjs-Message: 01:57:55.638: JS LOG: [LookingGlass/info] loaded at Wed Dec 25 2019 01:57:55 GMT+0700 (WIB)
Cjs-Message: 01:57:55.638: JS LOG: Cinnamon started at Wed Dec 25 2019 01:57:55 GMT+0700 (WIB)
Cjs-Message: 01:57:55.652: JS LOG: [LookingGlass/info] ExtensionSystem started in 0 ms
Cjs-Message: 01:57:55.653: JS LOG: [LookingGlass/info] DeskletManager started in 0 ms
Cjs-Message: 01:57:55.653: JS LOG: [LookingGlass/info] SearchProviderManager started in 0 ms
openGL version 3.1 detected (GL3 Cogl Driver)
Cjs-Message: 01:57:55.707: JS LOG: [LookingGlass/info] Adding indicator: nm-applet
Cjs-Message: 01:57:55.736: JS LOG: [LookingGlass/info] Loaded applet show-desktop@cinnamon.org in 24 ms
Cjs-Message: 01:57:55.758: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 22 ms
Cjs-Message: 01:57:55.764: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 6 ms
Cjs-Message: 01:57:55.778: JS LOG: [LookingGlass/info] Loaded applet user@cinnamon.org in 14 ms
St-Message: 01:57:55.781: cogl npot texture sizes SUPPORTED
Cjs-Message: 01:57:55.785: JS LOG: [LookingGlass/info] Role locked: notifications
Cjs-Message: 01:57:55.790: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 12 ms
Cjs-Message: 01:57:55.801: JS LOG: [LookingGlass/info] Loaded applet keyboard@cinnamon.org in 10 ms
Cjs-Message: 01:57:55.805: JS LOG: [LookingGlass/info] Role locked: tray
Cjs-Message: 01:57:55.819: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 18 ms
Cjs-Message: 01:57:55.827: JS LOG: [LookingGlass/info] Loaded applet xapp-status@cinnamon.org in 8 ms
Cjs-Message: 01:57:55.838: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 10 ms

(cinnamon:1838): Gtk-WARNING **: 01:57:55.865: Attempting to read the recently used resources file at '/home/ijash/.local/share/recently-used.xbel', but the parser failed: Failed to open file “/home/ijash/.local/share/recently-used.xbel”: Permission denied.
Cjs-Message: 01:57:55.870: JS LOG: [LookingGlass/info] Role locked: panellauncher
Cjs-Message: 01:57:55.871: JS LOG: [LookingGlass/info] Loaded applet grouped-window-list@cinnamon.org in 32 ms

(csd-power:1671): power-plugin-CRITICAL **: 01:57:55.895: abs_to_percentage: assertion 'max > min' failed
Cjs-Message: 01:57:55.923: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 52 ms
Cjs-Message: 01:57:55.944: JS LOG: [LookingGlass/info] Hiding indicator (role already handled): nm-applet
Cjs-Message: 01:57:55.947: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 24 ms
Cjs-Message: 01:57:56.121: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 172 ms
Cjs-Message: 01:57:56.121: JS LOG: [LookingGlass/info] AppletManager started in 482 ms
Cjs-Message: 01:57:56.123: JS LOG: [LookingGlass/info] Cinnamon took 682 ms to start
Cjs-Message: 01:57:56.133: JS LOG: Unknown network device type, is 14
/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py:84: Warning: g_base64_encode_step: assertion 'in != NULL' failed
  css = provider.to_string()
Cjs-Message: 01:58:15.938: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintUpdate.py (org.x.StatusIcon.PID-1974-0)
Cjs-Message: 01:58:39.082: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintreport (org.x.StatusIcon.PID-2125-0)
Cjs-Message: 03:34:14.640: JS LOG: [LookingGlass/info] Adding indicator: transmission
** Message: 03:34:38.838: Unable to select area using GNOME Shell's builtin screenshot interface, resorting to fallback X11.
Gtk-Message: 03:35:29.688: GtkDialog mapped without a transient parent. This is discouraged.
Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3a00003 (Authentica)
** Message: 03:35:44.109: Unable to select area using GNOME Shell's builtin screenshot interface, resorting to fallback X11.
Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4200085 (syslog [Re)
```

I have found this conversation on the [forum](https://forums.linuxmint.com/viewtopic.php?t=293438)
but I have not tried the solution when this report was posted.

Any further assistance or instruction for this  *(probably)* bug, I'd like to give further relevant information .

**Comment by vpalos** [comment]
Did you find a solution for this issue? I'm experiencing exactly the same behavior on a recently (freshly) installed Ubuntu 20.04.

**Comment by vpalos** [comment]
For anyone who might encounter this thread, I've solved my problem by running this command:
```sh
sudo ubuntu-drivers autoinstall
```
After running (and installing a bunch of packages) the selected installed driver became the recommended one (run `ubuntu-drivers devices` to find out what that is). Don't forget to reboot afterwards.

**Comment by realfoodman** [comment]
These two things worked for me on Ubuntu 12.10. Thank you! After running the commands and rebooting, the screen was at low resolution, so I switched to the next-newest driver (which is what Ubuntu had selected by default after being installed) and rebooted again. Smooth sailing since then.

**Comment by mtwebster** [comment]
Is this still occurring in the current version of the driver manager? (1.5.2).

**Comment by mghoffmann** [comment]
Yes, it is. I'm trying to solve it right now. For me it started after installing NVidia Cuda following the instructions at https://developer.nvidia.com/cuda-downloads.

**Comment by kmanwar89** [comment]
> For anyone who might encounter this thread, I've solved my problem by running this command:
> 
> ```shell
> sudo ubuntu-drivers autoinstall
> ```
> 
> After running (and installing a bunch of packages) the selected installed driver became the recommended one (run `ubuntu-drivers devices` to find out what that is). Don't forget to reboot afterwards.

Since this issue is still open...I faced this exact issue on a fresh install of Ubuntu 22.04. Running the command from @vpalos worked for me as well! Thank you for posting the solution.

**Comment by jabowery** [comment]
```
# ubuntu-drivers autoinstall
Traceback (most recent call last):
  File "/usr/bin/ubuntu-drivers", line 513, in <module>
    greet()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/bin/ubuntu-drivers", line 432, in autoinstall
    command_install(config)
  File "/usr/bin/ubuntu-drivers", line 187, in command_install
    UbuntuDrivers.detect.nvidia_desktop_pre_installation_hook(to_install)
  File "/usr/lib/python3/dist-packages/UbuntuDrivers/detect.py", line 839, in nvidia_desktop_pre_installation_hook
    with_nvidia_kms = version >= 470
UnboundLocalError: local variable 'version' referenced before assignment

```

**Comment by DolceParadise** [comment]
> ```
> # ubuntu-drivers autoinstall
> Traceback (most recent call last):
>   File "/usr/bin/ubuntu-drivers", line 513, in <module>
>     greet()
>   File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/click/decorators.py", line 84, in new_func
>     return ctx.invoke(f, obj, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/bin/ubuntu-drivers", line 432, in autoinstall
>     command_install(config)
>   File "/usr/bin/ubuntu-drivers", line 187, in command_install
>     UbuntuDrivers.detect.nvidia_desktop_pre_installation_hook(to_install)
>   File "/usr/lib/python3/dist-packages/UbuntuDrivers/detect.py", line 839, in nvidia_desktop_pre_installation_hook
>     with_nvidia_kms = version >= 470
> UnboundLocalError: local variable 'version' referenced before assignment
> ```

I am getting the same error on `sudo ubuntu-drivers autoinstall`
Is there a workaround for this?

**Comment by DjSapsan** [comment]
Solution:
sudo apt purge *nvidia*
sudo apt autoremove
sudo apt install --reinstall libgl1-mesa-glx libgl1-mesa-dri xserver-xorg-core xserver-xorg-video-nouveau libdrm-nouveau2

then logout and in

suddenly everything is selectable!

**Comment by Committing** [comment]
> @DolceParadise replace the line 853 with `version = int(package_name.split('-')[-2])` in `/usr/lib/python3/dist-packages/UbuntuDrivers/detect.py`

Thanks, it is line 835 now.

**Comment by edison23** [comment]
Installing the `nvidia-driver-525` explicitly using APT fixed it for me: https://askubuntu.com/a/1463002/333914

**Comment by Aakash-chouksey** [comment]
> @DolceParadise replace the line 853 with `version = int(package_name.split('-')[-2])` in `/usr/lib/python3/dist-packages/UbuntuDrivers/detect.py`

worked for me. I was facing the issue of black screen after boot so i change the driver to nouveau driver from the during the bootup process after that my drivers got locked to "continue using manually installed driver " in the ubuntu addition drivers 

after  making this changes and rebooting i was able to change my driver from addition driver setting but it is still facing the blackout screen problem

I have one more question should i be using the nvidia drivers open(porprietary,tested ) ones or just the one proprietary option 
thank you in advance
